const questionBank = [
  {
    id: "strategy-choice",
    kicker: "集体判断",
    title: "你会选择哪一种策略？",
    description: "你不知道其他人的答案。多数与少数，都可能成为这一轮的优势。",
    options: [
      { id: "A", title: "谨慎", detail: "固定获得 1 分" },
      { id: "B", title: "共识", detail: "人数最多得 3 分" },
      { id: "C", title: "独行", detail: "人数最少得 4 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "C" },
    rule: { type: "safe-majority-minority", safe: "A", majority: "B", minority: "C" },
  },
  {
    id: "peace-agreement",
    kicker: "信任边界",
    title: "签署和平协议，还是打破协议？",
    description: "合作能带来更高收益，但两名破坏者就足以让协议失效。",
    options: [
      { id: "A", title: "签署协议", detail: "破坏者少于 2 人时获得 3 分" },
      { id: "B", title: "打破协议", detail: "固定获得 1 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "cooperation", cooperate: "A", defect: "B", limit: 2 },
  },
  {
    id: "stag-hunt",
    kicker: "猎鹿博弈",
    title: "高价值目标出现，你选择联合还是独自行动？",
    description: "联合行动回报更高，但需要足够多人参加；独自行动收益较低，却不依赖他人。",
    options: [
      { id: "A", title: "联合行动", detail: "至少 60% 玩家选择时得 5 分，否则 0 分" },
      { id: "B", title: "独自行动", detail: "无论其他人如何选择，固定获得 2 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "A" },
    rule: { type: "stag-hunt", cooperate: "A", solo: "B", ratio: 0.6, successScore: 5, soloScore: 2 },
  },
  {
    id: "hawk-dove",
    kicker: "鹰鸽博弈",
    title: "面对唯一控制权，你选择协商还是强夺？",
    description: "强夺者只有一人时收益最高；多人同时强夺会发生冲突并被扣分。",
    options: [
      { id: "A", title: "协商", detail: "无人强夺得 3 分；一人强夺得 1 分；多人强夺得 2 分" },
      { id: "B", title: "强夺", detail: "仅一人强夺得 5 分；多人强夺每人扣 2 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "hawk-dove", dove: "A", hawk: "B", peacefulScore: 3, yieldedScore: 1, conflictObserverScore: 2, loneHawkScore: 5, conflictScore: -2 },
  },
  {
    id: "leader-risk",
    kicker: "领先者风险",
    title: "你愿意承担一次与排名有关的积分风险吗？",
    description: "这一题会读取本轮开始前的总积分。领先者与追赶者面对同一选项，风险完全不同。",
    options: [
      { id: "A", title: "接受排名风险", detail: "若当前并列最高分，总积分归零；否则积分不变" },
      { id: "B", title: "支付保险成本", detail: "无论排名如何，固定扣除 0.5 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "A" },
    rule: { type: "leader-risk", gamble: "A", insure: "B", insuranceCost: -0.5 },
  },
  {
    id: "public-fund",
    kicker: "公共选择",
    title: "是否加入公共基金？",
    description: "只有足够多人参与，基金才会启动。",
    options: [
      { id: "A", title: "加入基金", detail: "至少 60% 玩家加入时得 4 分，否则 0 分" },
      { id: "B", title: "暂不加入", detail: "固定获得 1 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "A" },
    rule: { type: "threshold", support: "A", wait: "B", ratio: 0.6, successScore: 4, waitScore: 1 },
  },
  {
    id: "shared-warehouse",
    kicker: "资源分配",
    title: "你要从共享仓库领取几份物资？",
    description: "仓库容量有限。索取过多，所有人的申请都会失败。",
    options: [
      { id: "A", title: "领取 1 份", detail: "总申请不超容量时获得 1 分" },
      { id: "B", title: "领取 2 份", detail: "总申请不超容量时获得 2 分" },
      { id: "C", title: "领取 3 份", detail: "总申请不超容量时获得 3 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "C" },
    rule: { type: "shared-capacity", capacityPerPlayer: 2, values: { A: 1, B: 2, C: 3 } },
  },
  {
    id: "single-ticket",
    kicker: "唯一竞价",
    title: "为唯一的船票选择一个竞价",
    description: "最高且只有一人选择的竞价获胜。过于拥挤的高价也会失效。",
    options: [
      { id: "A", title: "竞价 1", detail: "成为最高唯一竞价得 5 分，其他人得 1 分" },
      { id: "B", title: "竞价 2", detail: "成为最高唯一竞价得 5 分，其他人得 1 分" },
      { id: "C", title: "竞价 3", detail: "成为最高唯一竞价得 5 分，其他人得 1 分" },
      { id: "D", title: "竞价 4", detail: "成为最高唯一竞价得 5 分，其他人得 1 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "D" },
    rule: { type: "unique-high", values: { A: 1, B: 2, C: 3, D: 4 }, winScore: 5, otherScore: 1 },
  },
  {
    id: "average-guess",
    kicker: "群体预测",
    title: "猜一个最接近全体平均数 70% 的数字",
    description: "你不仅要判断数字，还要判断其他人会如何判断。",
    options: [
      { id: "A", title: "1", detail: "最接近目标值得 4 分，其他人得 1 分" },
      { id: "B", title: "2", detail: "最接近目标值得 4 分，其他人得 1 分" },
      { id: "C", title: "3", detail: "最接近目标值得 4 分，其他人得 1 分" },
      { id: "D", title: "4", detail: "最接近目标值得 4 分，其他人得 1 分" },
      { id: "E", title: "5", detail: "最接近目标值得 4 分，其他人得 1 分" },
    ],
    aiChoices: { conservative: "C", aggressive: "E" },
    rule: { type: "closest-average", factor: 0.7, values: { A: 1, B: 2, C: 3, D: 4, E: 5 }, winScore: 4, otherScore: 1 },
  },
  {
    id: "signal-tower",
    kicker: "全体共识",
    title: "独立维修，还是同步重启信号塔？",
    description: "同步重启收益很高，但必须得到所有人的一致选择。",
    options: [
      { id: "A", title: "独立维修", detail: "固定获得 1 分" },
      { id: "B", title: "同步重启", detail: "全员都选择时每人得 5 分，否则 0 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "unanimity-risk", safe: "A", risk: "B", safeScore: 1, successScore: 5 },
  },
  {
    id: "crowd-forecast",
    kicker: "人数预测",
    title: "选择一个你认为会有相近人数选择的数字",
    description: "比较“选项数字”与“实际选择该项的人数”。误差最小者加 2 分，误差最大者扣 1 分。",
    options: [
      { id: "A", title: "1", detail: "若最终约有 1 人选择，本项误差较小" },
      { id: "B", title: "2", detail: "若最终约有 2 人选择，本项误差较小" },
      { id: "C", title: "3", detail: "若最终约有 3 人选择，本项误差较小" },
      { id: "D", title: "4", detail: "若最终约有 4 人选择，本项误差较小" },
    ],
    aiChoices: { conservative: "C", aggressive: "D" },
    rule: { type: "crowd-forecast", values: { A: 1, B: 2, C: 3, D: 4 }, bestScore: 2, worstScore: -1 },
  },
  {
    id: "team-auction",
    kicker: "团队竞价",
    title: "选择一个出价，争夺 20 积分奖池",
    description: "相同出价者组成团队。出价×人数为团队总出价，最高团队获得奖池，扣除总出价后由队员平分。",
    options: [
      { id: "A", title: "出价 1 分", detail: "团队总出价＝1×本项人数" },
      { id: "B", title: "出价 2 分", detail: "团队总出价＝2×本项人数" },
      { id: "C", title: "出价 3 分", detail: "团队总出价＝3×本项人数" },
      { id: "D", title: "出价 4 分", detail: "团队总出价＝4×本项人数" },
      { id: "E", title: "出价 5 分", detail: "团队总出价＝5×本项人数" },
      { id: "F", title: "出价 6 分", detail: "团队总出价＝6×本项人数" },
      { id: "G", title: "出价 7 分", detail: "团队总出价＝7×本项人数" },
      { id: "H", title: "出价 8 分", detail: "团队总出价＝8×本项人数" },
      { id: "I", title: "出价 9 分", detail: "团队总出价＝9×本项人数" },
      { id: "J", title: "出价 10 分", detail: "团队总出价＝10×本项人数" },
    ],
    aiChoices: { conservative: "C", aggressive: "H" },
    rule: { type: "team-auction", pool: 20, values: { A: 1, B: 2, C: 3, D: 4, E: 5, F: 6, G: 7, H: 8, I: 9, J: 10 } },
  },
  {
    id: "congestion-game",
    kicker: "拥挤博弈",
    title: "热门活动容量有限，你选择参加还是避开？",
    description: "参加者不超过全体 40% 时体验最佳；一旦过度拥挤，留下的人反而获得更高收益。",
    options: [
      { id: "A", title: "参加活动", detail: "未超过容量得 4 分；过度拥挤得 0 分" },
      { id: "B", title: "留在原地", detail: "未拥挤得 1 分；过度拥挤得 3 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "A" },
    rule: { type: "congestion", attend: "A", stay: "B", capacityRatio: 0.4, attendSuccess: 4, attendCrowded: 0, stayQuiet: 1, stayCrowded: 3 },
  },
  {
    id: "volunteer-dilemma",
    kicker: "志愿者困境",
    title: "团队需要至少一人承担任务，你愿意主动承担吗？",
    description: "只要有一名志愿者，任务就会完成；等待者收益更高，但所有人都等待则全员零分。",
    options: [
      { id: "A", title: "主动承担", detail: "任务必定完成，志愿者获得 2 分" },
      { id: "B", title: "等待他人", detail: "有人承担时得 3 分；无人承担时得 0 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "volunteer-dilemma", volunteer: "A", wait: "B", volunteerScore: 2, freeRideScore: 3 },
  },
  {
    id: "minimum-effort",
    kicker: "最低努力博弈",
    title: "为团队项目选择你的努力等级",
    description: "团队产出由全体最低努力决定，但个人需要承担自己的努力成本。得分＝最低努力×2－个人努力＋2。",
    options: [
      { id: "A", title: "努力 1", detail: "成本最低，但会限制全队产出" },
      { id: "B", title: "努力 2", detail: "较低投入" },
      { id: "C", title: "努力 3", detail: "中等投入" },
      { id: "D", title: "努力 4", detail: "较高投入" },
      { id: "E", title: "努力 5", detail: "成本最高，需要相信所有人" },
    ],
    aiChoices: { conservative: "B", aggressive: "E" },
    rule: { type: "minimum-effort", values: { A: 1, B: 2, C: 3, D: 4, E: 5 }, multiplier: 2, base: 2 },
  },
  {
    id: "bank-run",
    kicker: "银行挤兑",
    title: "市场出现传言，你选择立即取款还是继续持有？",
    description: "提前取款人数不超过全体 30% 时银行稳定；超过临界值就会发生挤兑。",
    options: [
      { id: "A", title: "立即取款", detail: "银行稳定得 2 分；发生挤兑仍得 1 分" },
      { id: "B", title: "继续持有", detail: "银行稳定得 4 分；发生挤兑得 0 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "bank-run", withdraw: "A", hold: "B", safeRatio: 0.3, withdrawSafe: 2, withdrawRun: 1, holdSafe: 4, holdRun: 0 },
  },
  {
    id: "lottery-investment",
    kicker: "彩票投入",
    title: "为随机抽取的 6 分奖金购买多少张票？",
    description: "每张票增加中奖概率，也会立即扣除 1 分。系统按票数随机抽出一名获奖者。",
    options: [
      { id: "A", title: "不买票", detail: "不扣分，也不会中奖" },
      { id: "B", title: "购买 1 张", detail: "扣 1 分，获得 1 份中奖权重" },
      { id: "C", title: "购买 2 张", detail: "扣 2 分，获得 2 份中奖权重" },
    ],
    aiChoices: { conservative: "A", aggressive: "C" },
    rule: { type: "lottery", prize: 6, tickets: { A: 0, B: 1, C: 2 } },
  },
  {
    id: "all-pay-auction",
    kicker: "全支付拍卖",
    title: "竞拍价值 6 分的奖励，你愿意出价多少？",
    description: "最高出价者获得奖励；无论是否获胜，所有人都必须支付自己的出价。并列最高者平分奖励。",
    options: [
      { id: "A", title: "出价 1 分", detail: "未获胜也会扣除 1 分" },
      { id: "B", title: "出价 2 分", detail: "未获胜也会扣除 2 分" },
      { id: "C", title: "出价 3 分", detail: "未获胜也会扣除 3 分" },
      { id: "D", title: "出价 4 分", detail: "未获胜也会扣除 4 分" },
      { id: "E", title: "出价 5 分", detail: "未获胜也会扣除 5 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "E" },
    rule: { type: "all-pay-auction", prize: 6, bids: { A: 1, B: 2, C: 3, D: 4, E: 5 } },
  },
  {
    id: "travelers-dilemma",
    kicker: "旅行者困境",
    title: "两件相同物品损坏，你要申报多少赔偿？",
    description: "所有人都按最低申报额获得基础赔偿；最低申报者额外加 2 分，其他人再扣 2 分。",
    options: [
      { id: "A", title: "申报 2 分", detail: "可能压低所有人的基础赔偿，但可获得最低申报奖励" },
      { id: "B", title: "申报 4 分", detail: "基础赔偿由全体最低申报决定" },
      { id: "C", title: "申报 6 分", detail: "基础赔偿由全体最低申报决定" },
      { id: "D", title: "申报 8 分", detail: "基础赔偿由全体最低申报决定" },
      { id: "E", title: "申报 10 分", detail: "高申报只有在其他人同样克制时才有价值" },
    ],
    aiChoices: { conservative: "A", aggressive: "E" },
    rule: { type: "travelers-dilemma", claims: { A: 2, B: 4, C: 6, D: 8, E: 10 }, bonus: 2, penalty: 2 },
  },
  {
    id: "cyclic-dominance",
    kicker: "循环克制",
    title: "选择石头、布或剪刀，与全场其他玩家逐一结算",
    description: "每战胜一名玩家加 1 分，每负于一名玩家扣 1 分，相同选择互不计分。",
    options: [
      { id: "A", title: "石头", detail: "战胜剪刀，负于布" },
      { id: "B", title: "布", detail: "战胜石头，负于剪刀" },
      { id: "C", title: "剪刀", detail: "战胜布，负于石头" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "cyclic-dominance", beats: { A: "C", B: "A", C: "B" } },
  },
];

module.exports = { questionBank };
