const questionBank = [
  {
    id: "strategy-choice",
    kicker: "集体判断",
    title: "你会选择哪一种策略？",
    description: "你不知道其他人的答案。多数与少数，都可能成为这一轮的优势。",
    options: [
      { id: "A", title: "谨慎", detail: "固定获得 1 分" },
      { id: "B", title: "共识", detail: "人数最多得 3 分" },
      { id: "C", title: "独行", detail: "人数最少得 4 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "C" },
    rule: { type: "safe-majority-minority", safe: "A", majority: "B", minority: "C" },
  },
  {
    id: "peace-agreement",
    kicker: "信任边界",
    title: "签署和平协议，还是打破协议？",
    description: "合作能带来更高收益，但两名破坏者就足以让协议失效。",
    options: [
      { id: "A", title: "签署协议", detail: "破坏者少于 2 人时获得 3 分" },
      { id: "B", title: "打破协议", detail: "固定获得 1 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "cooperation", cooperate: "A", defect: "B", limit: 2 },
  },
  {
    id: "stag-hunt",
    kicker: "猎鹿博弈",
    title: "高价值目标出现，你选择联合还是独自行动？",
    description: "联合行动回报更高，但需要足够多人参加；独自行动收益较低，却不依赖他人。",
    options: [
      { id: "A", title: "联合行动", detail: "至少 60% 玩家选择时得 5 分，否则 0 分" },
      { id: "B", title: "独自行动", detail: "无论其他人如何选择，固定获得 2 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "A" },
    rule: { type: "stag-hunt", cooperate: "A", solo: "B", ratio: 0.6, successScore: 5, soloScore: 2 },
  },
  {
    id: "hawk-dove",
    kicker: "鹰鸽博弈",
    title: "面对唯一控制权，你选择协商还是强夺？",
    description: "强夺者只有一人时收益最高；多人同时强夺会发生冲突并被扣分。",
    options: [
      { id: "A", title: "协商", detail: "无人强夺得 3 分；一人强夺得 1 分；多人强夺得 2 分" },
      { id: "B", title: "强夺", detail: "仅一人强夺得 5 分；多人强夺每人扣 2 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "hawk-dove", dove: "A", hawk: "B", peacefulScore: 3, yieldedScore: 1, conflictObserverScore: 2, loneHawkScore: 5, conflictScore: -2 },
  },
  {
    id: "two-teams",
    kicker: "动态平衡",
    title: "你要加入左队还是右队？",
    description: "两队越均衡，所有人收益越稳定；失衡时少数方反而获利。",
    options: [
      { id: "A", title: "加入左队", detail: "人数差不超过 1 得 3 分；否则少数 4 分、多数 1 分" },
      { id: "B", title: "加入右队", detail: "人数差不超过 1 得 3 分；否则少数 4 分、多数 1 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "balance", balancedScore: 3, minorityScore: 4, majorityScore: 1 },
  },
  {
    id: "public-fund",
    kicker: "公共选择",
    title: "是否加入公共基金？",
    description: "只有足够多人参与，基金才会启动。",
    options: [
      { id: "A", title: "加入基金", detail: "至少 60% 玩家加入时得 4 分，否则 0 分" },
      { id: "B", title: "暂不加入", detail: "固定获得 1 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "A" },
    rule: { type: "threshold", support: "A", wait: "B", ratio: 0.6, successScore: 4, waitScore: 1 },
  },
  {
    id: "shared-warehouse",
    kicker: "资源分配",
    title: "你要从共享仓库领取几份物资？",
    description: "仓库容量有限。索取过多，所有人的申请都会失败。",
    options: [
      { id: "A", title: "领取 1 份", detail: "总申请不超容量时获得 1 分" },
      { id: "B", title: "领取 2 份", detail: "总申请不超容量时获得 2 分" },
      { id: "C", title: "领取 3 份", detail: "总申请不超容量时获得 3 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "C" },
    rule: { type: "shared-capacity", capacityPerPlayer: 2, values: { A: 1, B: 2, C: 3 } },
  },
  {
    id: "single-ticket",
    kicker: "唯一竞价",
    title: "为唯一的船票选择一个竞价",
    description: "最高且只有一人选择的竞价获胜。过于拥挤的高价也会失效。",
    options: [
      { id: "A", title: "竞价 1", detail: "成为最高唯一竞价得 5 分，其他人得 1 分" },
      { id: "B", title: "竞价 2", detail: "成为最高唯一竞价得 5 分，其他人得 1 分" },
      { id: "C", title: "竞价 3", detail: "成为最高唯一竞价得 5 分，其他人得 1 分" },
      { id: "D", title: "竞价 4", detail: "成为最高唯一竞价得 5 分，其他人得 1 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "D" },
    rule: { type: "unique-high", values: { A: 1, B: 2, C: 3, D: 4 }, winScore: 5, otherScore: 1 },
  },
  {
    id: "average-guess",
    kicker: "群体预测",
    title: "猜一个最接近全体平均数 70% 的数字",
    description: "你不仅要判断数字，还要判断其他人会如何判断。",
    options: [
      { id: "A", title: "1", detail: "最接近目标值得 4 分，其他人得 1 分" },
      { id: "B", title: "2", detail: "最接近目标值得 4 分，其他人得 1 分" },
      { id: "C", title: "3", detail: "最接近目标值得 4 分，其他人得 1 分" },
      { id: "D", title: "4", detail: "最接近目标值得 4 分，其他人得 1 分" },
      { id: "E", title: "5", detail: "最接近目标值得 4 分，其他人得 1 分" },
    ],
    aiChoices: { conservative: "C", aggressive: "E" },
    rule: { type: "closest-average", factor: 0.7, values: { A: 1, B: 2, C: 3, D: 4, E: 5 }, winScore: 4, otherScore: 1 },
  },
  {
    id: "signal-tower",
    kicker: "全体共识",
    title: "独立维修，还是同步重启信号塔？",
    description: "同步重启收益很高，但必须得到所有人的一致选择。",
    options: [
      { id: "A", title: "独立维修", detail: "固定获得 1 分" },
      { id: "B", title: "同步重启", detail: "全员都选择时每人得 5 分，否则 0 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "unanimity-risk", safe: "A", risk: "B", safeScore: 1, successScore: 5 },
  },
  {
    id: "evacuation-choice",
    kicker: "撤离判断",
    title: "警报响起时，你选择怎样撤离？",
    description: "稳妥、从众和冒险都可能得分，关键在于其他人的决定。",
    options: [
      { id: "A", title: "等待指引", detail: "固定获得 1 分" },
      { id: "B", title: "跟随人群", detail: "人数最多得 3 分" },
      { id: "C", title: "独自寻找出口", detail: "人数最少得 4 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "C" },
    rule: { type: "safe-majority-minority", safe: "A", majority: "B", minority: "C" },
  },
  {
    id: "bridge-order",
    kicker: "秩序考验",
    title: "过桥时，你会排队还是抢先？",
    description: "少数人抢先不会破坏秩序，但第二个人可能改变所有人的收益。",
    options: [
      { id: "A", title: "按顺序通过", detail: "抢先者少于 2 人时获得 3 分" },
      { id: "B", title: "抢先通过", detail: "固定获得 1 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "cooperation", cooperate: "A", defect: "B", limit: 2 },
  },
  {
    id: "base-location",
    kicker: "共同规划",
    title: "新基地应该建在哪里？",
    description: "被最多人支持的地点将成为最终方案。",
    options: [
      { id: "A", title: "临海区", detail: "人数最多得 3 分；并列第一得 2 分" },
      { id: "B", title: "城市中心", detail: "人数最多得 3 分；并列第一得 2 分" },
      { id: "C", title: "郊野区", detail: "人数最多得 3 分；并列第一得 2 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "A" },
    rule: { type: "majority", winScore: 3, tieScore: 2 },
  },
  {
    id: "secret-symbol",
    kicker: "少数挑战",
    title: "选择一个你认为最冷门的符号",
    description: "选择人数最少的符号得分最高。没有人选择的符号不参与比较。",
    options: [
      { id: "A", title: "圆", detail: "人数最少得 4 分，其他人得 1 分" },
      { id: "B", title: "三角", detail: "人数最少得 4 分，其他人得 1 分" },
      { id: "C", title: "方形", detail: "人数最少得 4 分，其他人得 1 分" },
      { id: "D", title: "六边形", detail: "人数最少得 4 分，其他人得 1 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "D" },
    rule: { type: "minority", winScore: 4, otherScore: 1 },
  },
  {
    id: "channel-choice",
    kicker: "航道平衡",
    title: "你选择左侧航道还是右侧航道？",
    description: "均衡分流最安全，严重拥堵时较少的一侧收益更高。",
    options: [
      { id: "A", title: "左侧航道", detail: "人数差不超过 1 得 3 分；否则少数 4 分、多数 1 分" },
      { id: "B", title: "右侧航道", detail: "人数差不超过 1 得 3 分；否则少数 4 分、多数 1 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "balance", balancedScore: 3, minorityScore: 4, majorityScore: 1 },
  },
  {
    id: "expedition-team",
    kicker: "集体冒险",
    title: "是否参加未知区域探险？",
    description: "探险队达到七成规模才会出发，留下的人则获得稳定收益。",
    options: [
      { id: "A", title: "参加探险", detail: "至少 70% 玩家参加时得 4 分，否则 0 分" },
      { id: "B", title: "留守基地", detail: "固定获得 1 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "A" },
    rule: { type: "threshold", support: "A", wait: "B", ratio: 0.7, successScore: 4, waitScore: 1 },
  },
  {
    id: "energy-request",
    kicker: "能源博弈",
    title: "你要申请多少单位的公共能源？",
    description: "总申请量不超过每人平均 2 单位时按申请得分，否则全员归零。",
    options: [
      { id: "A", title: "申请 1 单位", detail: "总量未超限时获得 1 分" },
      { id: "B", title: "申请 2 单位", detail: "总量未超限时获得 2 分" },
      { id: "C", title: "申请 3 单位", detail: "总量未超限时获得 3 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "C" },
    rule: { type: "shared-capacity", capacityPerPlayer: 2, values: { A: 1, B: 2, C: 3 } },
  },
  {
    id: "captain-bid",
    kicker: "职位竞价",
    title: "为临时船长席位选择一个编号",
    description: "最高且只有一人选择的编号获胜；热门选择可能互相抵消。",
    options: [
      { id: "A", title: "编号 1", detail: "成为最高唯一编号得 5 分，其他人得 1 分" },
      { id: "B", title: "编号 2", detail: "成为最高唯一编号得 5 分，其他人得 1 分" },
      { id: "C", title: "编号 3", detail: "成为最高唯一编号得 5 分，其他人得 1 分" },
      { id: "D", title: "编号 4", detail: "成为最高唯一编号得 5 分，其他人得 1 分" },
    ],
    aiChoices: { conservative: "B", aggressive: "D" },
    rule: { type: "unique-high", values: { A: 1, B: 2, C: 3, D: 4 }, winScore: 5, otherScore: 1 },
  },
  {
    id: "meeting-time",
    kicker: "时间预测",
    title: "猜一个最接近全体平均值的集合时间",
    description: "最接近大家平均选择的时间获得高分。",
    options: [
      { id: "A", title: "08:00", detail: "最接近平均时间得 4 分，其他人得 1 分" },
      { id: "B", title: "09:00", detail: "最接近平均时间得 4 分，其他人得 1 分" },
      { id: "C", title: "10:00", detail: "最接近平均时间得 4 分，其他人得 1 分" },
      { id: "D", title: "11:00", detail: "最接近平均时间得 4 分，其他人得 1 分" },
      { id: "E", title: "12:00", detail: "最接近平均时间得 4 分，其他人得 1 分" },
    ],
    aiChoices: { conservative: "C", aggressive: "E" },
    rule: { type: "closest-average", factor: 1, values: { A: 8, B: 9, C: 10, D: 11, E: 12 }, winScore: 4, otherScore: 1 },
  },
  {
    id: "shared-password",
    kicker: "终极共识",
    title: "保留旧口令，还是启用共同新口令？",
    description: "新口令只有在所有人同步启用时才会生效。",
    options: [
      { id: "A", title: "保留旧口令", detail: "固定获得 1 分" },
      { id: "B", title: "启用新口令", detail: "全员都选择时每人得 5 分，否则 0 分" },
    ],
    aiChoices: { conservative: "A", aggressive: "B" },
    rule: { type: "unanimity-risk", safe: "A", risk: "B", safeScore: 1, successScore: 5 },
  },
];

module.exports = { questionBank };
